# Generated by Django 3.1.3 on 2020-11-17 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_history', models.BooleanField()),
                ('repair_report', models.TextField()),
                ('manufacturer', models.CharField(choices=[('1', '현대'), ('2', '르노 삼성'), ('3', '기아'), ('4', '쌍용'), ('5', 'GM 대우'), ('6', '기타')], max_length=1)),
                ('foreign_car', models.BooleanField()),
                ('desired_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PictureCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('car_information_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carinfo.carinformation')),
            ],
        ),
    ]
