# Generated by Django 3.1.3 on 2020-11-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinformation',
            name='manufacturer',
            field=models.CharField(choices=[('1', '현대'), ('2', '르노 삼성'), ('3', '기아'), ('4', '쌍용'), ('5', 'GM 대우'), ('6', '기타')], max_length=1),
        ),
    ]
